<input type="checkbox" id="ヘイラッシャ_e"><label for="ヘイラッシャ_e">ヘイラッシャ</label>
<input type="checkbox" id="ハバタクカミ_e"><label for="ハバタクカミ_e">ハバタクカミ</label>
<input type="checkbox" id="ロトム(ウォッシュ)_e"><label for="ロトム(ウォッシュ)_e">ロトム(ウォッシュ)</label>
<input type="checkbox" id="オーガポン(かまど)_e"><label for="オーガポン(かまど)_e">オーガポン(かまど)</label>
<input type="checkbox" id="イーユイ_e"><label for="イーユイ_e">イーユイ</label>
<input type="checkbox" id="テツノカイナ_e"><label for="テツノカイナ_e">テツノカイナ</label>
<input type="checkbox" id="ガブリアス_e"><label for="ガブリアス_e">ガブリアス</label>
<input type="checkbox" id="ヌメルゴン(ヒスイ)_e"><label for="ヌメルゴン(ヒスイ)_e">ヌメルゴン(ヒスイ)</label>
<input type="checkbox" id="ランドロス(けしん)_e"><label for="ランドロス(けしん)_e">ランドロス(けしん)</label>
<input type="checkbox" id="イイネイヌ_e"><label for="イイネイヌ_e">イイネイヌ</label>